vault/config/routes.rb
Vault::Application.routes.draw do

  get "providers/index"
  get "websites/ratings"

  post "website_comments/new"
  get "website_comments/index"

  post "websites/visit"

  resources :services do
    collection do
      get "all_omniauths"
    end
  end

  get "sites/like"
  get "sites/dislike"
  get "sites/mark_as_visited"
  get "sites/get_recommendation"

  get "pages/index"
  get "pages/about"
  get "pages/help"

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "services"}

  root :to => "pages#index"

end

vault/app/models/facebook.rb
class Facebook < Service
  def post_comment(comment)
    Rails.logger.info "000000000#{comment}"
    @graph = Koala::Facebook::API.new(token)
    @graph.put_connections("me", "feed", :message => comment)
  end
end

vault/app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :website
  belongs_to  :ownable, polymorphic: true
  attr_accessible :forwarding_url, :original_created_at, :perview_image_url, :preview_text, :website_id

end

vault/app/models/provider.rb
class Provider < ActiveRecord::Base
  attr_accessible :name, :logo_url
  has_many :services
end

vault/app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :provider
  belongs_to :user
  attr_accessible :secret, :token, :uid, :user

  def self.from_omniauth(auth)
    provider = Provider.find_or_create_by_name(auth.provider)
    unless service = provider.services.find_by_uid(auth.uid)
      service = provider.services.create!( uid: auth.uid, token: auth.credentials.token, secret: auth.credentials.secret)
      service.update_attributes!(user: service.create_user!)
    end
    return service
  end

  def post_comment(comment)

  end

end

vault/app/models/service_comment.rb
class ServiceComment < WebsiteComment

end

vault/app/models/shortened_url.rb
class ShortenedUrl < ActiveRecord::Base
  belongs_to :website
  attr_accessible :url
end

vault/app/models/twitter.rb
class Twitter < Service

  def post_comment(comment)
    #@client = Twitter::Client.new(
    #  :oauth_token => token,
    #  :oauth_token_secret => secret
    #)
    #@client.update(comment) if @client
  end

end

vault/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  validates_presence_of   :password, :on => :create, :unless => :joined_account?
  validates_uniqueness_of    :email,     :case_sensitive => false, :allow_blank => true, :if => :email_changed?
  validates_format_of :email, :with  => Devise.email_regexp, :allow_blank => true, :if => :email_changed?
  validates_confirmation_of   :password, :on=>:create
  validates_length_of :password, :within => Devise.password_length, :allow_blank => true

  has_many  :services
  has_many  :providers, :through => :services
  has_many  :visits
  has_many  :websites, through: :visits

  has_many  :website_comments, as: :ownable
  has_many  :vault_comments, as: :ownable

  def visit(url, visited_rating = nil)
    visited_website = Website.find_or_create_by_url(url)
    visits.find_or_create_by_website_id(visited_website.id)
    visits.where(website_id: visited_website.id).first_or_create do |website|
      website.website_id = visited_website.id
      website.rating = visited_rating
    end
  end

private

  def joined_account?
    services.exists?
  end

end

vault/app/models/vault_comment.rb
class VaultComment < WebsiteComment

end

vault/app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :user
  belongs_to :website
  attr_accessible :rating

  def self.ratings
    { rating_image_unselected_url: "/star_empty_64.png", rating_image_selected_url: "/star_filled_gimp.png", number_of_ratings: 5 }
  end
end

vault/app/models/website.rb
class Website < ActiveRecord::Base
  attr_accessible :url
  has_many :visits
  has_many :website_comments

  validates :url, uniqueness: true
end

vault/app/models/website_comment.rb
class WebsiteComment < Item

end

vault/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def help
  end
end

vault/app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  def index
    @providers = Provider.order("updated_at desc")
    render json: @providers
  end
end

vault/app/controllers/services_controller.rb
class ServicesController < ApplicationController
  # GET /services
  # GET /services.json
  def index
    @services = Service.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @services }
    end
  end

  # GET /services/1
  # GET /services/1.json
  def show
    @service = Service.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @service }
    end
  end

  # GET /services/new
  # GET /services/new.json
  def new
    @service = Service.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @service }
    end
  end

  # GET /services/1/edit
  def edit
    @service = Service.find(params[:id])
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(params[:service])

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render json: @service, status: :created, location: @service }
      else
        format.html { render action: "new" }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /services/1
  # PUT /services/1.json
  def update
    @service = Service.find(params[:id])

    respond_to do |format|
      if @service.update_attributes(params[:service])
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service = Service.find(params[:id])
    @service.destroy

    respond_to do |format|
      format.html { redirect_to services_url }
      format.json { head :no_content }
    end
  end

  def all_omniauths
    service = Service.from_omniauth(request.env["omniauth.auth"])
    if service.persisted?
      Rails.logger.info "uid + #{service.id} + user + #{service.user}"
      flash.notice = "Signed in!"
      sign_in_and_redirect service.user
    else
      redirect_to new_user_registration_url
    end
  end

  alias_method :facebook, :all_omniauths
  alias_method :twitter, :all_omniauths

end

vault/app/controllers/websites_controller.rb
class WebsitesController < ApplicationController

  #in the next version, this should all be in visits controller
  #currently passing in -1 as default value for rating
  def visit
    @website = visit_and_get_website(params[:url], params[:rating])
    Rails.logger.info params
    respond_to do |format|
      format.html { render :json => "response", status: "success" }
    end
  end

  def ratings
    render json: Visit.ratings
  end

end

vault/app/helpers/application_helper.rb
module ApplicationHelper
end

vault/app/helpers/pages_helper.rb
module PagesHelper
end

vault/app/helpers/providers_helper.rb
module ProvidersHelper
end

vault/app/helpers/services_helper.rb
module ServicesHelper
end

vault/app/helpers/shortened_urls_helper.rb
module ShortenedUrlsHelper
end

vault/app/helpers/website_comments_helper.rb
module WebsiteCommentsHelper
end

vault/app/helpers/websites_helper.rb
module WebsitesHelper
end

vault/app/views/providers/index.html.erb
<h1>Providers#index</h1>
<p>Find me in app/views/providers/index.html.erb</p>

vault/app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :provider %><br />
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :uid %><br />
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :token %><br />
    <%= f.text_field :token %>
  </div>
  <div class="field">
    <%= f.label :secret %><br />
    <%= f.text_field :secret %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

vault/app/views/services/edit.html.erb
<h1>Editing service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

vault/app/views/services/index.html.erb
<h1>Listing services</h1>

<table>
  <tr>
    <th>Provider</th>
    <th>User</th>
    <th>Uid</th>
    <th>Token</th>
    <th>Secret</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @services.each do |service| %>
  <tr>
    <td><%= service.provider %></td>
    <td><%= service.user %></td>
    <td><%= service.uid %></td>
    <td><%= service.token %></td>
    <td><%= service.secret %></td>
    <td><%= link_to 'Show', service %></td>
    <td><%= link_to 'Edit', edit_service_path(service) %></td>
    <td><%= link_to 'Destroy', service, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Service', new_service_path %>

vault/app/views/services/new.html.erb
<h1>New service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

vault/app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Provider:</b>
  <%= @service.provider %>
</p>

<p>
  <b>User:</b>
  <%= @service.user %>
</p>

<p>
  <b>Uid:</b>
  <%= @service.uid %>
</p>

<p>
  <b>Token:</b>
  <%= @service.token %>
</p>

<p>
  <b>Secret:</b>
  <%= @service.secret %>
</p>


<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>